<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;


class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Data=[
            [
                'book_name'=>'Hoàng Tử Bé (Tái Bản 2019)',
                'book_slug'=>Str::slug('Hoàng Tử Bé (Tái Bản 2019)'),
                'description'=>'Hoàng tử bé được viết ở New York trong những ngày tác giả sống lưu vong và được xuất bản lần đầu tiên tại New York vào năm 1943, rồi đến năm 1946 mới được xuất bản tại Pháp. Không nghi ngờ gì, đây là tác phẩm nổi tiếng nhất, được đọc nhiều nhất và cũng được yêu mến nhất của Saint-Exupéry. Cuốn sách được bình chọn là tác phẩm hay nhất thế kỉ 20 ở Pháp, đồng thời cũng là cuốn sách Pháp được dịch và được đọc nhiều nhất trên thế giới. Với 250 ngôn ngữ dịch khác nhau kể cả phương ngữ cùng hơn 200 triệu bản in trên toàn thế giới, Hoàng tử bé được coi là một trong những tác phẩm bán chạy nhất của nhân loại. Ở Việt Nam, Hoàng tử bé được dịch và xuất bản khá sớm. Từ năm 1966 đã có đồng thời hai bản dịch: Hoàng tử bé của Bùi Giáng do An Tiêm xuất bản và Cậu hoàng con của Trần Thiện Đạo do Khai Trí xuất bản. Từ đó đến nay đã có thêm nhiều bản dịch Hoàng tử bé mới của các dịch giả khác nhau. Bản dịch Hoàng tử bé lần này, xuất bản nhân dịp kỷ niệm 70 năm Hoàng tử bé ra đời, cũng là ấn bản đầu tiên được Gallimard chính thức chuyển nhượng bản quyền tại Việt Nam, hy vọng sẽ góp phần làm phong phú thêm việc dịch và tiếp nhận tác phẩm quan trọng này với các thế hệ độc giả.',
                'language'=>'1',
                'avatar'=>'26838e18d7f96d562d828980520019d2.jpg',
                'year_publish'=>'2019',
                'quantity'=>'750',
                'price'=>'75000',
                'NXB'=>null,
                'pages'=>'102',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'1'
            ],
            [
                'book_name'=>'Chuyện Con Mèo Dạy Hải Âu Bay (Tái Bản 2019)',
                'book_slug'=>Str::slug('Chuyện Con Mèo Dạy Hải Âu Bay (Tái Bản 2019)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2f8c27f60797dfc4c729b03b1272403b.jpg',
                'year_publish'=>'2019',
                'quantity'=>'1000',
                'price'=>'49000',
                'NXB'=>null,
                'pages'=>'144',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'2'
            ],
            [
                'book_name'=>'Siêu Nhí Hỏi Nhà Khoa Học Trả Lời - 100 Bí Ẩn Mọi Đứa Trẻ Đều Muốn Hỏi Một Nhà Khoa Học',
                'book_slug'=>Str::slug('Siêu Nhí Hỏi Nhà Khoa Học Trả Lời - 100 Bí Ẩn Mọi Đứa Trẻ Đều Muốn Hỏi Một Nhà Khoa Học'),
                'description'=>'Cuốn sách khoa học đáng yêu cho các bạn nhỏ này tập hợp 100 câu hỏi về cuộc sống hàng ngày từ các bạn học sinh trên khắp thế giới gửi đến nhà khoa học Robert Winston. Cuốn sách cho chúng ta thấy sự tò mò chung của trẻ em đối với thế giới xung quanh qua những câu hỏi những thu thập từ trẻ em ở Vương quốc Anh, các nước Châu u khác, Canada, Mỹ, Ấn Độ, Trung Quốc và Nhật Bản. Các câu hỏi xoay quanh những khía cạnh khác nhau của khoa học, bao trùm ở các chủ đề chính gồm cơ thể con người, vật lý, hóa học, không gian, khoa học tự nhiên và Trái Đất.',
                'language'=>'1',
                'avatar'=>'0440c2c596fe47add68be6a62ee36433.jpg',
                'year_publish'=>'2020',
                'quantity'=>'350',
                'price'=>'250000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'128',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'3'
            ],
            [
                'book_name'=>'Combo Truyện Tranh Song Ngữ Việt - Anh Cho Bé (12 Tập)',
                'book_slug'=>Str::slug('Combo Truyện Tranh Song Ngữ Việt - Anh Cho Bé (12 Tập)'),
                'description'=>'Bộ Truyện tranh song ngữ Việt-Anh cho bé gồm 12 tập là 12 câu chuyện được kể bằng tiếng Việt và tiếng Anh. Mỗi câu chuyện không chỉ mang đến những giờ phút giải trí vui vẻ, mà còn chứa đựng bài học bổ ích, khuyến khích các bé phát triển lối sống lành mạnh, có trách nhiệm, và giúp cải thiện vốn từ vựng tiếng Anh. Đây chắc chắn sẽ là món quà tuyệt vời để các bậc cha mẹ dành tặng cho những “nhà ngôn ngữ học bé nhỏ” của mình.',
                'language'=>'1',
                'avatar'=>'ba09a3f89d09449d64a53e91bf9dc042.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'125000',
                'NXB'=>'Nhà Xuất Bản Phụ Nữ',
                'pages'=>null,
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'4'
            ],
            [
                'book_name'=>'Những Truyện Hay Viết Cho Thiếu Nhi - Tô Hoài (Tái Bản 2019)',
                'book_slug'=>Str::slug('Những Truyện Hay Viết Cho Thiếu Nhi - Tô Hoài (Tái Bản 2019)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'26aeb8f6aa491d6331f5d6c18044d27b.jpg',
                'year_publish'=>'2019',
                'quantity'=>'500',
                'price'=>'80000',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>'304',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'6'
            ],
            [
                'book_name'=>'Sách Ehon - Combo 4 cuốn Bạn là ai vậy - Dành cho trẻ từ 0 - 3 tuổi',
                'book_slug'=>Str::slug('Sách Ehon - Combo 4 cuốn Bạn là ai vậy - Dành cho trẻ từ 0 - 3 tuổi'),
                'description'=>'“Động vật” là bộ sách Ehon gồm 4 cuốn “Bạn ăn gì vậy”; “Bạn là ai vậy”; “Bạn màu gì vậy”; “Bạn ở đâu vậy”. Bộ sách phù hợp với trẻ từ 3 tuổi và thông qua các câu chuyện đáng yêu sẽ giúp trẻ nhận biết các bạn khỉ, bạn sư tử, bạn cá heo và nhiều bạn khác. Qua đó phát triển Thùy trán – nơi kích thích trí tưởng tượng, giúp trẻ có khả năng tư duy logic, lập kế hoạch, giúp hình thành tính cách của bé, lớn lên bé sẽ rất giỏi trong việc giải quyết các vấn đề phức tạp và sắp xếp các công việc trong đời sống.',
                'language'=>'1',
                'avatar'=>'f792dab10a0f6da96b1faf37dbeda0e2.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'156000',
                'NXB'=>'Nhà Xuất Bản Lao Động Xã Hội',
                'pages'=>'24',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'7'
            ],
            [
                'book_name'=>'100 Kỹ Năng Sinh Tồn',
                'book_slug'=>Str::slug('100 Kỹ Năng Sinh Tồn'),
                'description'=>'Bạn sẽ làm gì nếu như một ngày bị mắc kẹt giữa vùng lãnh thổ có dịch bệnh hoành hành, lạc ở nơi hoang dã, bị móc túi khi đi du lịch ở đất nước xa lạ, hay phải thoát ngay khỏi một vụ hỏa hoạn ở nhà cao tầng… ? Clint Emerson – một cựu Đặc vụ SEAL, lực lượng tác chiến đặc biệt của Hải quân Hoa Kỳ – muốn bạn có được sự chuẩn bị tốt nhất trong cuốn sách 100 kỹ năng sinh tồn này.Rõ ràng, chi tiết và được trình bày dễ hiểu, cuốn sách này phác thảo chi tiết nhiều chiến lược giúp bảo vệ bạn và những người bạn yêu thương, dạy bạn cách suy nghĩ và hành động như một thành viên của lực lượng quân đội tinh nhuệ Hoa Kỳ. 100 kỹ năng sinh tồn thực sự là cuốn cẩm nang vô giá. Bởi lẽ, khi nguy hiểm xảy ra, bạn chẳng có nhiều thời gian cho những chỉ dẫn phức tạp đâu.',
                'language'=>'1',
                'avatar'=>'915e36b7629c4792218f19b57a8868e4.jpg',
                'year_publish'=>null,
                'quantity'=>'1000',
                'price'=>'99000',
                'NXB'=>'Nhà Xuất Bản Thanh Niên',
                'pages'=>'272',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'8'
            ],
            [
                'book_name'=>'Sách Ehon - Combo 3 cuốn Âm thanh quanh bé - Dành cho trẻ từ 0 - 6 tuổi',
                'book_slug'=>Str::slug('Sách Ehon - Combo 3 cuốn Âm thanh quanh bé - Dành cho trẻ từ 0 - 6 tuổi'),
                'description'=>'“Âm thanh” là bộ sách Ehon gồm 3 cuốn “Tùng tùng”; “Leng keng”; “ùm bò”;. Bộ sách phù hợp với trẻ từ 0-6 tuổi và thông qua các âm thanh thường ngày từ các đồ vật hay con vật sẽ giúp bé khám phá thế giới xung quanh. Qua đó phát triển Thùy thái dương – nơi phần não sử dụng ngôn ngữ nói, nghe, cảm xúc với âm nhạc, âm thanh, ngữ điệu. khi lớn lên con sẽ có kỹ năng giao tiếp rất tốt và luôn tự tin vào bản thân',
                'language'=>'1',
                'avatar'=>'2c0bfd6828ec1ba523f137aaf91391fb.png',
                'year_publish'=>'2020',
                'quantity'=>'600',
                'price'=>'117000',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'24',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'7'
            ],
            [
                'book_name'=>'Combo Tuổi Thơ Dữ Đội (2 cuốn) (Tái Bản 2019)',
                'book_slug'=>Str::slug('Combo Tuổi Thơ Dữ Đội (2 cuốn) (Tái Bản 2019)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'21a0273a20fd358f24a6c3d7f621a5cf.jpg',
                'year_publish'=>'2019',
                'quantity'=>'50',
                'price'=>'160000',
                'NXB'=>null,
                'pages'=>null,
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'9'
            ],
            [
                'book_name'=>'Ruột Ơi Là Ruột',
                'book_slug'=>Str::slug('Ruột Ơi Là Ruột'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'ruot.jpg',
                'year_publish'=>'2017',
                'quantity'=>'2000',
                'price'=>'100000',
                'NXB'=>null,
                'pages'=>'352',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'10'
            ],
            [
                'book_name'=>'Chú Bé Mang Pyjama Sọc (Tái Bản 2018)',
                'book_slug'=>Str::slug('Chú Bé Mang Pyjama Sọc (Tái Bản 2018)'),
                'description'=>'Rất khó miêu tả câu chuyện về Chú bé mang pyjama sọc này. Thường thì chúng tôi vẫn tiết lộ vài chi tiết về cuốn sách trên bìa, nhưng trong trường hợp này chúng tôi nghĩ làm như vậy sẽ làm hỏng cảm giác đọc của bạn. Chúng tôi nghĩ điều quan trọng là bạn nên đọc mà không biết trước nó kể về điều gì.Nếu bạn định bắt đầu đọc cuốn sách thật, bạn sẽ cùng được trải qua một hành trình với một cậu bé chín tuổi tên là Bruno (dù đây không hẳn là sách cho trẻ chín tuổi). Và chẳng sớm thì muộn bạn sẽ cùng Bruno đến một hàng rào. Những hàng rào như vậy vẫn tồn tại ở khắp nơi trên thế giới. Chúng tôi hy vọng không ai trong chúng ta phải vượt qua một hàng rào như vậy trong đời.',
                'language'=>'1',
                'avatar'=>'99b31589a12ac561e769081c4eb32d1f.jpg',
                'year_publish'=>'2018',
                'quantity'=>'78',
                'price'=>'68000',
                'NXB'=>null,
                'pages'=>'253',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'11'
            ],
            [
                'book_name'=>'Dế Mèn Phiêu Lưu Ký (Tái Bản 2019)',
                'book_slug'=>Str::slug('Dế Mèn Phiêu Lưu Ký (Tái Bản 2019)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'336cb89bfe1dfefcaea03be376cea7d8.jpg',
                'year_publish'=>'2019',
                'quantity'=>'1000',
                'price'=>'50000',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>'144',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'6'
            ],
            [
                'book_name'=>'Phát Triển Trí Tuệ Cảm Xúc- Cảm Xúc Của Con Màu Gì?',
                'book_slug'=>Str::slug('Phát Triển Trí Tuệ Cảm Xúc- Cảm Xúc Của Con Màu Gì?'),
                'description'=>'Bộ sách thiết thực này là kết hợp giữa những minh họa trực quan cao độ và chủ đề giáo dục trọng yếu. Tất các cuốn sách trong bộ đều có Phần câu hỏi thảo luận để hỗ trợ phụ huynh khơi gợi và dẫn dắt những cuộc trò chuyện với trẻ về cảm xúc, nỗi lo lắng, thất bại, sự tử tế, bảo vệ thân thể, bình đẳng giới và đa dạng giới, Bộ sách là công cụ giúp trẻ nói lên tiếng nói của mình và khuyến khích trẻ tham gia chủ động, tích cực vào việc học hỏi.',
                'language'=>'1',
                'avatar'=>'665837ece4f64c794b7cd591903edeb8.jpg',
                'year_publish'=>'2020',
                'quantity'=>'67',
                'price'=>'50000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'40',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'12'
            ],
            [
                'book_name'=>'Harry Potter Và Hòn Đá Phù Thủy - Tập 1 (Tái Bản 2017)',
                'book_slug'=>Str::slug('Harry Potter Và Hòn Đá Phù Thủy - Tập 1 (Tái Bản 2017)'),
                'description'=>'Khi một lá thư được gởi đến cho cậu bé Harry Potter bình thường và bất hạnh, cậu khám phá ra một bí mật đã được che giấu suốt cả một thập kỉ. Cha mẹ cậu chính là phù thủy và cả hai đã bị lời nguyền của Chúa tể Hắc ám giết hại khi Harry mới chỉ là một đứa trẻ, và bằng cách nào đó, cậu đã giữ được mạng sống của mình. Thoát khỏi những người giám hộ Muggle không thể chịu đựng nổi để nhập học vào trường Hogwarts, một trường đào tạo phù thủy với những bóng ma và phép thuật, Harry tình cờ dấn thân vào một cuộc phiêu lưu đầy gai góc khi cậu phát hiện ra một con chó ba đầu đang canh giữ một căn phòng trên tầng ba. Rồi Harry nghe nói đến một viên đá bị mất tích sở hữu những sức mạnh lạ kì, rất quí giá, vô cùng nguy hiểm, mà cũng có thể là mang cả hai đặc điểm trên.',
                'language'=>'1',
                'avatar'=>'ec0a4054a5e85ea308d35f643c884c98.jpg',
                'year_publish'=>'2017',
                'quantity'=>'3000',
                'price'=>'135000',
                'NXB'=>null,
                'pages'=>'366',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'13'
            ],
            [
                'book_name'=>'Những Tù Nhân Của Địa Lí - Khám Phá Sự Vận Hành Của Thế Giới Qua Những Tấm Bản Đồ - Phiên Bản Minh Hoạ Màu Dành Cho Độc Giả Trẻ',
                'book_slug'=>Str::slug('Những Tù Nhân Của Địa Lí - Khám Phá Sự Vận Hành Của Thế Giới Qua Những Tấm Bản Đồ - Phiên Bản Minh Hoạ Màu Dành Cho Độc Giả Trẻ'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'de1621358fb64d08a8f5c08e2a0e1130.jpg',
                'year_publish'=>null,
                'quantity'=>'1000',
                'price'=>'230000',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>'72',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'14'
            ],
            [
                'book_name'=>'Bản Đồ',
                'book_slug'=>Str::slug('Bản Đồ'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'574854f032ae36fc0d0a57b61f588965.jpg',
                'year_publish'=>'2020',
                'quantity'=>'78',
                'price'=>'345000',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'108',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'17'
            ],
            [
                'book_name'=>'Harry Potter Và Phòng Chứa Bí Mật - Tập 2 (Tái Bản 2017)',
                'book_slug'=>Str::slug('Harry Potter Và Phòng Chứa Bí Mật - Tập 2 (Tái Bản 2017)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'ce4848cc4700049bd7c70512b2238121.jpg',
                'year_publish'=>'2017',
                'quantity'=>'4000',
                'price'=>'150000',
                'NXB'=>null,
                'pages'=>'430',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'13'
            ],
            [
                'book_name'=>'Thân Gửi Sở Thú',
                'book_slug'=>Str::slug('Thân Gửi Sở Thú'),
                'description'=>'Thân gửi Sở thú là một trong những cuốn sách tranh kinh điển của thế giới, đã tròn 25 năm tuổi và vẫn luôn là một cuốn sách yêu thích của nhiều thế hệ độc giả nhí. Cuốn sách đặc biệt dành riêng cho trẻ từ 0-3 tuổi, với các mẫu câu và từ vựng đơn giản, sử dụng cấu trúc lặp. Điểm đặc biệt thú vị ở Thân gửi Sở thú là những miếng lật đem lại những bất ngờ thú vị cho các bé. Cuốn sách không chỉ giúp tăng cường vốn từ vựng thông qua việc đọc, mà còn thông qua các hoạt động chạm và cảm nhận.',
                'language'=>'1',
                'avatar'=>'13f94a46fa8a0cc203f90dcb7bb7ea95.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'79000',
                'NXB'=>'Nhà Xuất Bản Hội Nhà Văn',
                'pages'=>'50',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'19'
            ],
            [
                'book_name'=>'Con Yêu Bố Chừng Nào',
                'book_slug'=>Str::slug('Con Yêu Bố Chừng Nào'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'a433018046824b573358c79aa26624b4.jpg',
                'year_publish'=>'2021',
                'quantity'=>'30',
                'price'=>'79000',
                'NXB'=>'Nhà Xuất Bản Hội Nhà Văn',
                'pages'=>'32',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'20'
            ],
            [
                'book_name'=>'Cùng Bé Khám Phá 500 Điều Thú Vị Về Khoa Học (Sách Bản Quyền Micro Facts!)',
                'book_slug'=>Str::slug('Cùng Bé Khám Phá 500 Điều Thú Vị Về Khoa Học (Sách Bản Quyền Micro Facts!)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'f9a3786e301e1b82825137c1b89b6c60.jpg',
                'year_publish'=>null,
                'quantity'=>'500',
                'price'=>'109000',
                'NXB'=>'Nhà Xuất Bản Phụ Nữ Việt Nam',
                'pages'=>'304',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'1',
                'author_id'=>'22'
            ],
            [
                'book_name'=>'Giáo Trình Kinh Tế Chính Trị Mác – Lênin (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021',
                'book_slug'=>Str::slug('Giáo Trình Kinh Tế Chính Trị Mác – Lênin (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'6a5c49d0e64b233150faad9bd3386b73.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'59800',
                'NXB'=>'Nhà Xuất Bản Chính Trị Quốc Gia Sự Thật',
                'pages'=>'292',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Kinh Tế Học Vĩ Mô (2021)',
                'book_slug'=>Str::slug('Kinh Tế Học Vĩ Mô (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'a9874b7a7912a346db04cb0b40593cd5.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'288000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'292',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'24'
            ],
            [
                'book_name'=>'Giáo Trình Chủ Nghĩa Xã Hội Khoa Học (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021',
                'book_slug'=>Str::slug('Giáo Trình Chủ Nghĩa Xã Hội Khoa Học (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'7ef579c2f4374af3816b5709b054d636.jpg',
                'year_publish'=>'2021',
                'quantity'=>'800',
                'price'=>'57000',
                'NXB'=>'Nhà Xuất Bản Chính Trị Quốc Gia Sự Thật',
                'pages'=>'276',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Giáo Trình Triết Học Mác – Lênin (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021)',
                'book_slug'=>Str::slug('Giáo Trình Triết Học Mác – Lênin (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'0c3a491b7e23820a5907adef10ef8033.jpg',
                'year_publish'=>'2021',
                'quantity'=>'590',
                'price'=>'94000',
                'NXB'=>'Nhà Xuất Bản Chính Trị Quốc Gia Sự Thật',
                'pages'=>'496',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Giáo Trình Tư Tưởng Hồ Chí Minh (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021',
                'book_slug'=>Str::slug('Giáo Trình Tư Tưởng Hồ Chí Minh (Dành Cho Bậc Đại Học Hệ Không Chuyên Lý Luận Chính Trị) - Bộ mới năm 2021'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'5e7e4a36695c21a21e5cdc7bf3429abe.jpg',
                'year_publish'=>'2021',
                'quantity'=>'780',
                'price'=>'55000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'292',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Hệ Thống Bài Tập & Câu Hỏi Trắc Nghiệm Nguyên Lý Kế Toán)',
                'book_slug'=>Str::slug('Hệ Thống Bài Tập & Câu Hỏi Trắc Nghiệm Nguyên Lý Kế Toán)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2445d0bafddb2943c90e0b348461079c.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'30000',
                'NXB'=>'Nhà Xuất Bản Tài Chính',
                'pages'=>'139',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'25'
            ],
            [
                'book_name'=>'Giáo Trình C++ Và Lập Trình Hướng Đối Tượng',
                'book_slug'=>Str::slug('Giáo Trình C++ Và Lập Trình Hướng Đối Tượng'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'7c48a0e134d985f72b84f63727d6a09d.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'145000',
                'NXB'=>'Nhà Xuất Bản Bách Khoa Hà Nội',
                'pages'=>'488',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'26'
            ],
            [
                'book_name'=>'Lịch Sử 12 (2021)',
                'book_slug'=>Str::slug('Lịch Sử 12 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'126162476e66e7ee8e12b1f2be8c84a3.jpg',
                'year_publish'=>'2021',
                'quantity'=>'780',
                'price'=>'16000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'292',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Cơ sở di truyền học phân tử và tế bào',
                'book_slug'=>Str::slug('Cơ sở di truyền học phân tử và tế bào'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'086e3dde9f30efeb93a5c42ec7dd268d.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'165000',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nội',
                'pages'=>'614',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'28'
            ],
            [
                'book_name'=>'Ngữ Văn 12 - Tập 2 (2021)',
                'book_slug'=>Str::slug('Ngữ Văn 12 - Tập 2 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'5be1f08e136c70865bb94d0730dfc4b0.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'13000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'200',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Tiếng Việt 4 - Tập 2 (2021)',
                'book_slug'=>Str::slug('Tiếng Việt 4 - Tập 2 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'a7597cea78fa3044ed106cd7884a030f.jpg',
                'year_publish'=>'2021',
                'quantity'=>'780',
                'price'=>'14000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'200',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Giải Tích 12 (2021)',
                'book_slug'=>Str::slug('Giải Tích 12 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'e83bbc62ce3b738f46404e703999008b.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'10000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'150',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Đại Số Và Giải Tích 11 (2021)',
                'book_slug'=>Str::slug('Đại Số Và Giải Tích 11 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'735a05c28c11183f632e7da541320f66.jpg',
                'year_publish'=>'2021',
                'quantity'=>'40',
                'price'=>'11000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'150',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Giáo Dục Công Dân 11 (2021)',
                'book_slug'=>Str::slug('Giáo Dục Công Dân 11 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'82b0f2c595b6424d6f6e560320e3d1b4.jpg',
                'year_publish'=>'2021',
                'quantity'=>'30',
                'price'=>'7000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'70',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Tiếng Việt 3 - Tập 2 (2021)',
                'book_slug'=>Str::slug('Tiếng Việt 3 - Tập 2 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'07409846d12d71ee601b40297c425509.jpg',
                'year_publish'=>'2021',
                'quantity'=>'800',
                'price'=>'13000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'178',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Giáo Dục Quốc Phòng - An Ninh 11 (2021)',
                'book_slug'=>Str::slug('Giáo Dục Quốc Phòng - An Ninh 11 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'09386bd86378558245d00a16f162d931.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'10000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'150',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Sinh Học 11 (2021)',
                'book_slug'=>Str::slug('Sinh Học 11 (2021)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'61b7ea4842b4a3c9efdaa478a39e4703.jpg',
                'year_publish'=>'2021',
                'quantity'=>'780',
                'price'=>'16000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'200',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'23'
            ],
            [
                'book_name'=>'Pháp Luật Đại Cương - Dùng Trong Các Trường Đại Học, Cao Đẳng Và Trung Cấp (Xuất Bản Lần Thứ Mười Tám, Có Sửa Đổi, Bổ Sung)',
                'book_slug'=>Str::slug('Pháp Luật Đại Cương - Dùng Trong Các Trường Đại Học, Cao Đẳng Và Trung Cấp (Xuất Bản Lần Thứ Mười Tám, Có Sửa Đổi, Bổ Sung)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'1572825f0b95f9cb98419f5ccfbed0f4.jpg',
                'year_publish'=>'2021',
                'quantity'=>'35',
                'price'=>'130500',
                'NXB'=>'Nhà Xuất Bản Chính Trị Quốc Gia Sự Thật',
                'pages'=>'234',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'29'
            ],
            [
                'book_name'=>'Giáo Trình Lập Trình Cơ Sở',
                'book_slug'=>Str::slug('Giáo Trình Lập Trình Cơ Sở'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'19c7825df74d9206317241a33ae80ffc.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'110000',
                'NXB'=>'Nhà Xuất Bản Xây Dựng',
                'pages'=>'251',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'30'
            ],
            [
                'book_name'=>'Toán Rời Rạc Ứng Dụng Trong Tin Học',
                'book_slug'=>Str::slug('Toán Rời Rạc Ứng Dụng Trong Tin Học'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'1136015c9e57aaf1686e3f9760777743.jpg',
                'year_publish'=>'2021',
                'quantity'=>'78',
                'price'=>'105000',
                'NXB'=>'Nhà Xuất Bản Giáo Dục Việt Nam',
                'pages'=>'408',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'2',
                'author_id'=>'31'
            ],
            [
                'book_name'=>'Tâm Lý Học Về Tiền',
                'book_slug'=>Str::slug('Tâm Lý Học Về Tiền'),
                'description'=>'Tiền bạc có ở khắp mọi nơi, nó ảnh hưởng đến tất cả chúng ta, và khiến phần lớn chúng ta bối rối. Mọi người nghĩ về nó theo những cách hơi khác nhau một chút. Nó mang lại những bài học có thể được áp dụng tới rất nhiều lĩnh vực trong cuộc sống, như rủi ro, sự tự tin, và hạnh phúc. Rất ít chủ đề cung cấp một lăng kính phóng to đầy quyền lực giúp giải thích vì sao mọi người lại hành xử theo cách họ làm hơn là về tiền bạc. Đó mới là một trong những chương trình hoành tráng nhất trên thế giới.',
                'language'=>'1',
                'avatar'=>'14a42ae4f66c9b8b298aaef4b9671442.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'189000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'384',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'32'
            ],
            [
                'book_name'=>'Bí Mật Của Phan Thiên Ân',
                'book_slug'=>Str::slug('Bí Mật Của Phan Thiên Ân'),
                'description'=>'Những bài học về tinh thần, tâm linh và trí tuệ đã được chính tiến sĩ Alan Phan chắp bút & phóng tác lại theo nguyên tác của cuốn sách vô giá theo thời gian “Người bán hàng vĩ đại nhất thế giới” của Og Mandino.

                Lối viết dung dị, đơn giản: dùng một câu chuyện với bối cảnh thân thuộc và mười tờ kinh để thắp nên những bài học thay đổi cuộc đời – tất cả sẽ làm nên những sự thay đổi “diệu kì” khi ta áp dụng triệt để.
                
                Trong cuốn sách người đọc sẽ tìm thấy nhiều bất ngờ thú vị về việc khám phá chính bản thân và sức mạnh nội tại của mình qua ngòi bút “không-kinh-tế” và “đầy tính triết lý nhân sinh” của một “triết gia doanh nhân” bậc thầy Alan Phan.
                
                “Con đường để đạt được thành công và giàu có đều có những thử thách. Và để thành công hay giàu có cần phải có kinh nghiệm và bí quyết.
                 
                Tất cả những công thức thành công, hạnh phúc, bình an và tiền bạc của những người giàu nhất thế giới sẽ được gói gọn trong cuốn sách này qua 10 tờ kinh. Mỗi tờ kinh là những lời chỉ dạy của tiền nhân, chứa đựng một nguyên lý, một định luật, một sự thực căn bản mà người đọc phải thấu hiểu và ghi khắc vào tiềm thức. Khi bạn đã đưa những nguyên lý này vào tận bản năng, bạn sẽ có quyền lực để thâu lượm tất cả sự giàu sang mà bạn muốn.”',
                'language'=>'1',
                'avatar'=>'fd4d3cc6a9aa333b1efda6afbebeb8e5.jpg',
                'year_publish'=>'2018',
                'quantity'=>'50',
                'price'=>'69000',
                'NXB'=>null,
                'pages'=>'211',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'33'
            ],
            [
                'book_name'=>'Think And Grow Rich - 13 Nguyên Tắc Nghĩ Giàu, Làm Giàu (Tái Bản)',
                'book_slug'=>Str::slug('Think And Grow Rich - 13 Nguyên Tắc Nghĩ Giàu, Làm Giàu (Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'9c219e191737b2757911b962eeb54c2c.jpg',
                'year_publish'=>'2021',
                'quantity'=>'22',
                'price'=>'110000',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'399',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'34'
            ],
            [
                'book_name'=>'Think And Grow Rich - Nghĩ Giàu Và Làm Giàu',
                'book_slug'=>Str::slug('Think And Grow Rich - Nghĩ Giàu Và Làm Giàu'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'aa71f851071fc05bec537bec76dc4234.jpg',
                'year_publish'=>'2021',
                'quantity'=>'650',
                'price'=>'110000',
                'NXB'=>'Nhà Xuất Bản Tổng hợp TP.HCM',
                'pages'=>'450',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'34'
            ],
            [
                'book_name'=>'Nhà Lãnh Đạo Không Chức Danh',
                'book_slug'=>Str::slug('Nhà Lãnh Đạo Không Chức Danh'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'faef561228f4643b293ab087588dfced.jpg',
                'year_publish'=>'2021',
                'quantity'=>'33',
                'price'=>'80000',
                'NXB'=>null,
                'pages'=>'270',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'35'
            ],
            [
                'book_name'=>'Nhà Đầu Tư Thông Minh (Tái Bản 2020)',
                'book_slug'=>Str::slug('Nhà Đầu Tư Thông Minh (Tái Bản 2020)'),
                'description'=>'Là nhà tư vấn đầu tư vĩ đại nhất của thế kỷ 20, Benjamin Graham đã giảng dạy và truyền cảm hứng cho nhiều người trên khắp thế giới. Triết lý “đầu tư theo giá trị“ của Graham, bảo vệ nhà đầu tư khỏi những sai lầm lớn và dạy anh ta phát triển các chiến lược dài hạn, đã khiến Nhà đầu tư thông minh trở thành cẩm nang của thị trường chứng khoán kể từ lần xuất bản đầu tiên vào năm 1949.
                Trải qua năm tháng, diễn biến thị trường đã chứng minh tính sáng suốt trong các chiến lược của Graham. Trong khi vẫn giữ lại toàn vẹn văn bản ban đầu của Graham, ấn phẩm tái bản này bổ sung thêm bình luận cập nhật của ký giả chuyên về tài chính nổi tiếng Jason Zweig. Cái nhìn của Zweig bao quát hiện thực của thị trường ngày nay, vạch ra sự tương tự giữa những ví dụ của Graham và các tít báo về tài chính hiện nay, giúp bạn đọc có sự hiểu biết kỹ lưỡng hơn về cách thức áp dụng các nguyên tắc của Graham.',
                'language'=>'1',
                'avatar'=>'cefa8cc641e90ccc6c32d81008ecff98.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'199000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'644',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'36'
            ],
            [
                'book_name'=>'Người Giàu Có Nhất Thành Babylon (Tái Bản 2020)',
                'book_slug'=>Str::slug('Người Giàu Có Nhất Thành Babylon (Tái Bản 2020)'),
                'description'=>'Người giàu có nhất thành Babylon (tiếng Anh: The Richest Man in Babylon) được xem là một trong những tác phẩm truyền cảm hứng lớn nhất về chủ đề tiết kiệm, kế hoạch tài chính và sự giàu có cá nhân. Tác phẩm được viết bởi doanh nhân, nhà văn Mỹ George Samuel Clason vào năm 1926, kể về cách tiết kiệm, buôn bán và làm giàu của người dân ở thành Babylon cổ xưa.
                Ban đầu đây chỉ là một tập sách nhỏ, viết về các cách quản lý tài chính và do các ngân hàng và công ty bảo hiểm phân phối. Sau khi được tổng hợp, biên tập thành một cuốn sách trọn vẹn, “Người giàu có nhất thành Babylon” bất ngờ trở nên phổ biến và nổi tiếng trên toàn thế giới bởi những lời khuyên về quản lý tài chính hết sức khôn ngoan.               
                Cuốn sách tập hợp nhiều câu chuyện cổ về các nhân vật vươn lên từ nghèo khổ để trở nên giàu có, được kính trọng bậc nhất thành Babylon. Có thể kể đến câu chuyện của “người giàu có nhất thành Babylon” Arkad – một thợ khắc gỗ khi còn trẻ, hay người cho vay vàng Mathon, những người nô lệ như Dabasir, Megiddo, Sharru Nada,…',
                'language'=>'1',
                'avatar'=>'b23586292aa7019e802bd2a115d47645.jpg',
                'year_publish'=>'2020',
                'quantity'=>'10',
                'price'=>'98000',
                'NXB'=>'Nhà Xuất Bản Tổng hợp TP.HCM',
                'pages'=>'216',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'37'
            ],
            [
                'book_name'=>'Trải Nghiệm Khách Hàng Xuất Sắc',
                'book_slug'=>Str::slug('Trải Nghiệm Khách Hàng Xuất Sắc'),
                'description'=>'Bạn đang cầm trên tay cuốn sách Trải nghiệm khách hàng xuất sắc được viết từ hơn 22 năm kinh nghiệm, qua nhiều vị trí, môi trường khác nhau của ông Nguyễn Dương, một chuyên gia cấp quốc tế, một trong những người nhiệt huyết và chuyên sâu nhất về trải nghiệm khách hàng.
                Ngoài kinh nghiệm thực tế và kiến thức về quản trị nói chung và quản trị trải nghiệm khách hàng nói riêng, trong quá trình hoàn thành cuốn sách này, tác giả Nguyễn Dương đã thực hiện những đợt đi nghiên cứu nhiều công ty, bao gồm những chuyến đi, những cuộc nói chuyện, phỏng vấn, trao đổi, tìm hiểu và cập nhật cách mà nhiều công ty đã thực hiện để có thể cung cấp những trải nghiệm khách hàng tuyệt vời và tăng trưởng vượt bậc.               
                Bên cạnh đó, tác giả nghiên cứu cả những lý do và rào cản khiến các chiến lược trải nghiệm khách hàng thất bại. Những nguyên lý và phương pháp đã phát huy hiệu quả và trường tồn theo thời gian, được đúc kết từ nhiều trải nghiệm, bối cảnh, quy mô và môi trường khác nhau, trong và ngoài nước.
                ',
                'language'=>'1',
                'avatar'=>'0bf56803d20835319d0fe96b475553c6.jpg',
                'year_publish'=>'2020',
                'quantity'=>'500',
                'price'=>'250000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'344',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'38'
            ],
            [
                'book_name'=>'Khéo Ăn Nói Sẽ Có Được Thiên Hạ ( Tái Bản )',
                'book_slug'=>Str::slug('Khéo Ăn Nói Sẽ Có Được Thiên Hạ ( Tái Bản )'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'c55f8c043e5ff5842aa15dc1f3b6c20f.jpg',
                'year_publish'=>'2020',
                'quantity'=>'10',
                'price'=>'110000',
                'NXB'=>null,
                'pages'=>'406',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'39'
            ],
            [
                'book_name'=>'Chiến Tranh Tiền Tệ: Sự Thống Trị Của Quyền Lực Tài Chính (Phần 2)',
                'book_slug'=>Str::slug('Chiến Tranh Tiền Tệ: Sự Thống Trị Của Quyền Lực Tài Chính (Phần 2)'),
                'description'=>'Trong ấn bản lần thứ nhất của cuốn sách này, tác giả đưa ra ba dự đoán quan trọng.

                Thứ nhất, kinh tế Âu Mỹ sẽ rơi vào tình cảnh tiêu điều trường kỳ (chí ít là 10 năm), cho dù có nới lỏng chính sách về tiền tệ, hay kích thích chính sách tài chính – về cơ bản đều vô hiệu;
                
                Thứ hai, khi đó “lượng khí thải carbon” vẫn là một khái niệm tương đối xa lạ với xã hội Trung Quốc, sẽ phát huy tác dụng ngày càng quan trọng đối với kinh tế và xã hội, và sẽ bị “tài chính hóa” và “tiền tệ hóa”;
                
                Thứ 3, loại tiền tệ chủ quyền sẽ từng bước bị loại tiền tệ khu vực thay thế, và cuốn cùng sẽ tiến hóa hướng đến sự đơn nhất về tiền tệ trên thế giới.
                
                Và đến nay, ba dự đoán đó đều đã trở thành sự thực.
                
                Mục đích của cuốn sách này không phải là để dạy bạn cách đầu tư, cách phân bổ tài sản hay dạy một bộ phương pháp đối phó tiền tệ điển hình. Cuốn sách này nhằm trả lời những câu hỏi từ lâu đã khiến chúng ta bối rối và chưa được giải đáp: Tại sao tiền tệ lại có xung đột?
                
                Song Hongbing là một học giả rất tài năng trong lĩnh vực kinh tế thế giới. Ông đã dành nhiều thời gian để khám phá lịch sử, nghiên cứu thực tế và cố gắng diễn giải tương lai. Để viết lên cuốn sách thứ hai của mình mang tên Chiến tranh tiền tệ: sự thống trị của quyền lực tài chính, Song Hongbing đã đọc hơn 100 cuốn sách và truy nguyên đến hơn 300 năm trước để khám phá nguồn gốc của hệ thống tài chính hiện tại. Khi đọc cuốn sách này với sự thích thú, bạn sẽ cảm nhận được những đổi thay của thời gian và những thăm trầm của lịch sử.
                
                Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....',
                'language'=>'1',
                'avatar'=>'79b327f90a26240f4acb9feb71267009.jpg',
                'year_publish'=>'2022',
                'quantity'=>500,
                'price'=>'151500',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'614',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'40'
            ],
            [
                'book_name'=>'Cách thức kinh doanh và đầu cơ cổ phiếu! – How to Trade in Stocks',
                'book_slug'=>Str::slug('Cách thức kinh doanh và đầu cơ cổ phiếu! – How to Trade in Stocks'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'571a0937c2c64cf7b07fe9eec3979de5.png',
                'year_publish'=>'2022',
                'quantity'=>'5000',
                'price'=>'349000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'320',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'41'
            ],
            [
                'book_name'=>'Làm giàu từ chứng khoán bằng phương pháp VSA chính gốc: Nghiên cứu chuyên sâu về cách giao dịch của Wyckoff',
                'book_slug'=>Str::slug('Làm giàu từ chứng khoán bằng phương pháp VSA chính gốc: Nghiên cứu chuyên sâu về cách giao dịch của Wyckoff'),
                'description'=>'Phương pháp Wyckoff là một phương pháp được rất nhiều nhà đầu tư trên thế giới yêu thích sử dụng và được chứng minh hiệu quả trong suốt gần 100 năm qua trên thị trường tài chính thế giới. Phương pháp Wyckoff phân tích dựa trên nền tảng của giá và khối lượng cùng với 3 quy luật cơ bản của Wyckoff (Quy luật Cung – Cầu, Quy luật Nguyên nhân – Tác động và Quy luật Nỗ lực – Kết quả) nhằm giúp các nhà đầu tư nhận biết được sự hiện diện của “dòng tiền thông minh” để tìm ra những cơ hội giao dịch tốt nhất cho các nhà đầu tư.',
                'language'=>'1',
                'avatar'=>'e9dd9fe06362f7e4f719483e2fb01736.png',
                'year_publish'=>'2021',
                'quantity'=>'10',
                'price'=>'499000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'278',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'42'
            ],
            [
                'book_name'=>'45 Giây Tạo Nên Thay Đổi - Thấu Hiểu Tiếp Thị Mạng Lưới',
                'book_slug'=>Str::slug('45 Giây Tạo Nên Thay Đổi - Thấu Hiểu Tiếp Thị Mạng Lưới'),
                'description'=>'Tiếp thị mạng lưới là ngành kinh doanh đang phát triển nhanh, tuy nhiên ngày nay có rất nhiều sự nhầm lẫn về ngành kinh doanh này, đặc biệt là sự nhầm lẫn nó với mô hình kinh doanh đa cấp kim tự tháp, vốn mang tính phi pháp. Don Failla - một người có rất nhiều kinh nghiệm trong lĩnh vực tiếp thị mạng lưới từ những năm 1970 đã viết cuốn sách này nhằm giúp người đọc hiểu được bản chất tiếp thị mạng lưới thực ra là gì và không phải là gì. Qua cuốn sách tác giả cũng hướng dẫn cách trình bày hiệu quả về tiếp thị mạng lưới để người khác hiểu, và quan trọng là cách xây dựng một sự nghiệp riêng xung quanh mô hình kinh doanh này.',
                'language'=>'1',
                'avatar'=>'71ab34591cebf167204f4e85b7c61b18.jpg',
                'year_publish'=>'2019',
                'quantity'=>'5',
                'price'=>'70000',
                'NXB'=>null,
                'pages'=>'192',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'43'
            ],
            [
                'book_name'=>'Nghệ Thuật đầu tư Dhandho - The Dhandho Investor',
                'book_slug'=>Str::slug('Nghệ Thuật đầu tư Dhandho - The Dhandho Investor'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'6f099903563fbf2614d49b7a5ef18013.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'238000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'384',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'45'
            ],
            [
                'book_name'=>'Bắt Đầu Với Câu Hỏi Tại Sao - Nghệ Thuật Truyền Cảm Hứng Trong Kinh Doanh (Tái Bản)',
                'book_slug'=>Str::slug('Bắt Đầu Với Câu Hỏi Tại Sao - Nghệ Thuật Truyền Cảm Hứng Trong Kinh Doanh (Tái Bản)'),
                'description'=>'Lần đầu tiên khi tôi khám phá ra sức mạnh của lý do TẠI SAO là khi tôi cần đến nó trong cuộc đời mình. Nó không phải là kết quả của việc theo đuổi con đường học vấn của tôi. Nó đã xuất hiện khi tôi không còn cảm hứng với công việc của mình và cảm thấy vô cùng chán nản và thất vọng. Thực tế là đã không có vấn đề gì xảy ra với công việc của tôi, mà do tôi đã đánh mất niềm vui trong công việc mình làm. Nếu xét trên phương diện bề ngoài thì tôi nên vui mới phải. Tôi đã nhận được những khoản thù lao tốt và được làm việc với những đối tác tuyệt vời. Nhưng tôi đã trở nên vô cảm với những gì mình làm. Tôi không còn cảm thấy hài lòng với công việc của mình và cần tìm ra cách để nhóm lên ngọn lửa nhiệt huyết và đam mê thêm một lần nữa.

                Việc khám phá tầm quan trọng của lý do TẠI SAO đã hoàn toàn thay đổi cái nhìn của tôi về thế giới. Và việc khám phá ra lý do TẠI SAO của chính mình đã giúp tôi tìm lại được niềm đam mê còn cháy bỏng hơn gấp bội so với trước đây. Tôi đã chia sẻ ý tưởng vô cùng đơn giản, mạnh mẽ và thực tế này với bạn bè. Khi học hỏi được điều gì có giá trị, chúng tôi thường chia sẻ nó với những người mình yêu mến. Thật tuyệt vời vì những người bạn tôi đã bắt đầu có những thay đổi lớn lao trong cuộc đời. Và họ đã mời tôi chia sẻ ý tưởng này với bạn bè của họ và những người mà họ yêu mến. Từ đó ý tưởng này bắt đầu được lan truyền.
                
                Chính tại thời điểm này tôi đã quyết định biến mình thành vật thí nghiệm. Bởi vì tôi không thể chia sẻ và đề cao một khái niệm mà chính tôi cũng không thực hiện. Vì vậy tôi đã cố gắng thực hành nó nhiều nhất có thể. Lý do duy nhất khiến tôi được như ngày hôm nay, được sống và làm việc với lý do TẠI SAO của mình, đó là nhờ sự giúp đỡ của tất cả mọi người.',
                'language'=>'1',
                'avatar'=>'2de388901fba8f60681479aa9ffd245a.jpg',
                'year_publish'=>'2021',
                'quantity'=>'6',
                'price'=>'109000',
                'NXB'=>'Nhà Xuất Bản Công Thương',
                'pages'=>'346',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'46'
            ],
            [
                'book_name'=>'Tư Duy Phản Biện',
                'book_slug'=>Str::slug('Tư Duy Phản Biện'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'80b2a6075864f509d332757b6bcfaac4.jpg',
                'year_publish'=>'2022',
                'quantity'=>'500',
                'price'=>'85000',
                'NXB'=>null,
                'pages'=>'170',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'47'
            ],
            [
                'book_name'=>'Tuần Làm Việc 4 Giờ (Tái Bản)',
                'book_slug'=>Str::slug('Tuần Làm Việc 4 Giờ (Tái Bản)'),
                'description'=>'Timothy Ferress – tác giả của cuốn sách Tuần làm việc 4 giờ đã chỉ cho bạn thấy những suy nghĩ và mục tiêu sống của bạn đang có vấn đề. Bạn cần thay đổi để vừa có thể tận hưởng được cuộc sống vừa hoàn thành tốt công việc của mình.

                Dù ước mơ của bạn là gì: thoát khỏi cuộc đua tranh khốc liệt, du lịch tận hưởng cuộc sống, đi du ngoạn dài ngày, thiết lập kỷ lục thế giới hay chỉ đơn giản là thay đổi công việc, cuốn sách này sẽ cung cấp những công cụ cần thiết để biến ước mơ đó thành hiện thực ngay lúc này, ngay tại đây thay vì đợi đến khi nghỉ hưu. Luôn có cách nhận được phần thưởng cho sự nỗ lực vượt qua những khó khăn của cuộc sống thay vì phải đợi đến tận cuối đời.',
                'language'=>'1',
                'avatar'=>'95e5f93cba3e99425e849c888e895e59.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'115000',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'342',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'48'
            ],
            [
                'book_name'=>'Sách Tài Chính Cá Nhân Cho Người Việt Nam',
                'book_slug'=>Str::slug('Sách Tài Chính Cá Nhân Cho Người Việt Nam'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2d35f5288ea643e3768c8f3361cafa5a.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1',
                'price'=>'200000',
                'NXB'=>'Nhà Xuất Bản Phụ Nữ',
                'pages'=>'384',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'49'
            ],
            [
                'book_name'=>'Đừng Bao Giờ Đi Ăn Một Mình (Tái Bản)',
                'book_slug'=>Str::slug('Đừng Bao Giờ Đi Ăn Một Mình (Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'9f680d49c05be61065c81a6e6fce4faa.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'112000',
                'NXB'=>null,
                'pages'=>'388',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'50'
            ],
            [
                'book_name'=>'Tại Sao Chúng Tôi Muốn Bạn Giàu',
                'book_slug'=>Str::slug('Tại Sao Chúng Tôi Muốn Bạn Giàu'),
                'description'=>'Họ là những doanh nhân hàng đầu, có một không hai của thế giới, nổi tiếng và thành đạt. Họ khác nhau ở điểm xuất phát nhưng sẽ cùng nhau chỉ bạn điểm xuất phát cho sự giàu có bằng chính kinh nghiệm của họ. Từ quan niệm “cho người ta một con cá, và bạn nuôi sống anh ta một ngày. Dạy người ta câu cá, và bạn nuôi sống anh ta cả đời” hai nhà tỷ phú hàng đầu sẽ cho bạn thấy tại sao tiền bạc làm nên sự giàu có nhưng lại không giúp ta thoát khỏi sự nghèo khó.

                Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng',
                'language'=>'1',
                'avatar'=>'1374dacd8738da96e849ee393c1a28d8.jpg',
                'year_publish'=>'2007',
                'quantity'=>'5000',
                'price'=>'110000',
                'NXB'=>null,
                'pages'=>'429',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'3',
                'author_id'=>'52'
            ],
            [
                'book_name'=>'Tự Học 2000 Từ Vựng Tiếng Anh Theo Chủ Đề',
                'book_slug'=>Str::slug('Tự Học 2000 Từ Vựng Tiếng Anh Theo Chủ Đề'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'fc00028419754638dd5b250abbcb0de7.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'65000',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nội',
                'pages'=>'260',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'54'
            ],
            [
                'book_name'=>'Giải Thích Ngữ Pháp Tiếng Anh (Với Bài Tập Và Đáp Án) (Tái Bản)',
                'book_slug'=>Str::slug('Giải Thích Ngữ Pháp Tiếng Anh (Với Bài Tập Và Đáp Án) (Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'7763d9035552760f627c34acfec0e12f.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'220000',
                'NXB'=>'Nhà Xuất Bản Đà Nẵng',
                'pages'=>'560',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'55'
            ],
            [
                'book_name'=>'Tập Viết Chữ Hán Theo Giáo Trình Hán Ngữ Phiên Bản Mới',
                'book_slug'=>Str::slug('Tập Viết Chữ Hán Theo Giáo Trình Hán Ngữ Phiên Bản Mới'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'3e6f11e3003e973ce0d6b9a9bb25bf5f.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'88000',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nội',
                'pages'=>'195',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'57'
            ],
            [
                'book_name'=>'Mind Map English Vocabulary - Từ Vựng Tiếng Anh Qua Sơ Đồ Tư Duy',
                'book_slug'=>Str::slug('Mind Map English Vocabulary - Từ Vựng Tiếng Anh Qua Sơ Đồ Tư Duy'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'fa62fc7ca444357d28120ded12c87ff3.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'198000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'260',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'58'
            ],
            [
                'book_name'=>'Combo 2 Cuốn: Giáo Trình Hán Ngữ 3 Và Giáo Trình Hán Ngữ 4 (Tập 2 - Tái Bản)',
                'book_slug'=>Str::slug('Combo 2 Cuốn: Giáo Trình Hán Ngữ 3 Và Giáo Trình Hán Ngữ 4 (Tập 2 - Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'c1af9893559b972d98c8bb3417e97a61.png',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'190000',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nộia',
                'pages'=>null,
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'59'
            ],
            [
                'book_name'=>'IELTS No Vocab - No Worries !',
                'book_slug'=>Str::slug('IELTS No Vocab - No Worries !'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'3137e4182d0c3616a313575e0f323684.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'130000',
                'NXB'=>null,
                'pages'=>'196',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'60'
            ],
            [
                'book_name'=>'Giáo Trình Chuẩn HSK 1',
                'book_slug'=>Str::slug('Giáo Trình Chuẩn HSK 1'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'3e0bd4d2f16e4e5fa8d1c8cc59b55506.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'198000',
                'NXB'=>'Nhà Xuất Bản Tổng hợp TP.HCM',
                'pages'=>'144',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'61'
            ],
            [
                'book_name'=>'Học Tiếng Hàn Thật Là Đơn Giản - Trong Giao Tiếp Hàng Ngày',
                'book_slug'=>Str::slug('Học Tiếng Hàn Thật Là Đơn Giản - Trong Giao Tiếp Hàng Ngày'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'b412b7d0347e8c7a3ef1e21279ddf5a8.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'98000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'250',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'62'
            ],
            [
                'book_name'=>'Combo 4 Cuốn: Bộ Hackers IELTS Basic',
                'book_slug'=>Str::slug('Combo 4 Cuốn: Bộ Hackers IELTS Basic'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'ee063cabe0fbe9a0974a154e6ba944bc.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'676000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'1500',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'63'
            ],
            [
                'book_name'=>'Sổ Tay Từ Vựng Tiếng Hàn Thông Dụng',
                'book_slug'=>Str::slug('Sổ Tay Từ Vựng Tiếng Hàn Thông Dụng'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'bia.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'65000',
                'NXB'=>'Nhà Xuất Bản Từ Điển Bách Khoa',
                'pages'=>'1522',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'64'
            ],
            [
                'book_name'=>'Perfect IELTS Vocabulary',
                'book_slug'=>Str::slug('Perfect IELTS Vocabulary'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'34bc25dd3ac1ec6bef8dfbec80b5eea7.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'219500',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'600',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'66'
            ],
            [
                'book_name'=>'Hackers IELTS : Listening',
                'book_slug'=>Str::slug('Hackers IELTS : Listening'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'0a4395585acec83ed712d8cc690bf711.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'179000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'300',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'63'
            ],
            [
                'book_name'=>'Tập Viết Tiếng Hàn Dành Cho Người Mới Bắt Đầu',
                'book_slug'=>Str::slug('Tập Viết Tiếng Hàn Dành Cho Người Mới Bắt Đầu'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'e6eb39a355ca40d83a4db4539be0e635.jpg',
                'year_publish'=>'2021',
                'quantity'=>'2021',
                'price'=>'89000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'108',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'64'
            ],
            [
                'book_name'=>'Ielts Writing Step By Step (Bộ Sách Ielts Mike)',
                'book_slug'=>Str::slug('Ielts Writing Step By Step (Bộ Sách Ielts Mike)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'fc55fd0a9a58bffa3892bba6cae2793e.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'118000',
                'NXB'=>null,
                'pages'=>'172',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'67'
            ],
            [
                'book_name'=>'Ngữ Pháp Tiếng Hàn Thông Dụng - Trung Cấp',
                'book_slug'=>Str::slug('Ngữ Pháp Tiếng Hàn Thông Dụng - Trung Cấp'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'d018c5391cf6e04b195292bd794df486.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'250000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'432',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'68'
            ],
            [
                'book_name'=>'Sống Sót Nơi Công Sở English Business Writing - Viết Ư? Chuyện Nhỏ',
                'book_slug'=>Str::slug('Sống Sót Nơi Công Sở English Business Writing - Viết Ư? Chuyện Nhỏ'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'283b2223c55130aac518d3c61876056c.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'169000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'276',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'70'
            ],
            [
                'book_name'=>'BỘ SÁCH HỌC TIẾNG ANH lITTLE STORIES',
                'book_slug'=>Str::slug('BỘ SÁCH HỌC TIẾNG ANH lITTLE STORIES'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'ec71dd4029f0835376376f90117b6a50.png',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'650000',
                'NXB'=>null,
                'pages'=>'1900',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'71'
            ],
            [
                'book_name'=>'Giáo Trình Chuẩn HSK 1 - Bài Tập',
                'book_slug'=>Str::slug('Giáo Trình Chuẩn HSK 1 - Bài Tập'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'992aa0f601aa5386905695598ab4e299.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'158000',
                'NXB'=>'Nhà Xuất Bản Tổng hợp TP.HCM',
                'pages'=>'136',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'61'
            ],
            [
                'book_name'=>'Sổ Tay Từ Vựng Tiếng Hàn Thông Dụng Trình Độ A',
                'book_slug'=>Str::slug('Sổ Tay Từ Vựng Tiếng Hàn Thông Dụng Trình Độ A'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2469d20161212t100631129219.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'65000',
                'NXB'=>null,
                'pages'=>'386',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'64'
            ],
            [
                'book_name'=>'Sách - Combo 2 cuốn Hack Não 1500 phiên bản 2022 + Hack Não Ngữ Pháp',
                'book_slug'=>Str::slug('Sách - Combo 2 cuốn Hack Não 1500 phiên bản 2022 + Hack Não Ngữ Pháp'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'fea3d67fc8839936b3f3f4dc69c01e50.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'820000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'424',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'4',
                'author_id'=>'73'
            ],
            [
                'book_name'=>'Tâm Lý Học - Phác Họa Chân Dung Kẻ Phạm Tội',
                'book_slug'=>Str::slug('Tâm Lý Học - Phác Họa Chân Dung Kẻ Phạm Tội'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'4845a31ebb7c0b75766ef9272506f236.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'145000',
                'NXB'=>' Nhà xuất bản Thanh Niên',
                'pages'=>'280',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'74'
            ],
            [
                'book_name'=>'Thay Đổi Cuộc Sống Với Nhân Số Học',
                'book_slug'=>Str::slug('Thay Đổi Cuộc Sống Với Nhân Số Học'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'56b303e000cb42faada663569fc5d7c9.jpg',
                'year_publish'=>'2021',
                'quantity'=>'10',
                'price'=>'248000',
                'NXB'=>'Nhà xuất bản Tổng hợp TP.HCM',
                'pages'=>'342',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'75'
            ],
            [
                'book_name'=>'Càng Kỷ Luật, Càng Tự Do',
                'book_slug'=>Str::slug('Càng Kỷ Luật, Càng Tự Do'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'73b6578834e8aa8e5e071b64fab93d5d.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'109000',
                'NXB'=>'Nhà xuất bản Thế Giới',
                'pages'=>'288',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'76'
            ],
            [
                'book_name'=>'Chó sủa nhầm cây - Tại sao những gì ta biết về thành công có khi lại sai',
                'book_slug'=>Str::slug('Chó sủa nhầm cây - Tại sao những gì ta biết về thành công có khi lại sai'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'32e1ff66be34767100fb05932e514065.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'150000',
                'NXB'=>null,
                'pages'=>'320',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'75'
            ],
            [
                'book_name'=>'Đàn Ông Sao Hỏa Đàn Bà Sao Kim',
                'book_slug'=>Str::slug('Đàn Ông Sao Hỏa Đàn Bà Sao Kim'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'9e9180a632f9ad9703afb5fb6c86e12b.jpg',
                'year_publish'=>'2021',
                'quantity'=>'500',
                'price'=>'188000',
                'NXB'=>'Nhà xuất bản Hồng Đức',
                'pages'=>'488',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'77'
            ],
            [
                'book_name'=>'Hiểu Về Trái Tim (Tái Bản)',
                'book_slug'=>Str::slug('Hiểu Về Trái Tim (Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'7f4b9571a3119fb493a31cedb71edee9.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'138000',
                'NXB'=>null,
                'pages'=>'488',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'5',
                'author_id'=>'78'
            ],
            [
                'book_name'=>'Chinh Phục Luyện Thi Vào Lớp 10 Môn Tiếng Anh Theo Chủ Đề',
                'book_slug'=>Str::slug('Chinh Phục Luyện Thi Vào Lớp 10 Môn Tiếng Anh Theo Chủ Đề'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'c3857442f895570f80d2750dcc993eca.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'159000',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nội',
                'pages'=>'224',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'92'
            ],
            [
                'book_name'=>'Chinh Phục Luyện Thi Vào 10 Môn Ngữ Văn Theo Chủ Đề',
                'book_slug'=>Str::slug('Chinh Phục Luyện Thi Vào 10 Môn Ngữ Văn Theo Chủ Đề'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'08a4cf4f1a714acfcfbf52d3a3fb559b.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'104400',
                'NXB'=>'Nhà Xuất Bản Đại Học Quốc Gia Hà Nội',
                'pages'=>'296',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'92'
            ],
            [
                'book_name'=>'Đa Thức - Chuỗi Và Chuyên Đề Nâng Cao',
                'book_slug'=>Str::slug('Đa Thức - Chuỗi Và Chuyên Đề Nâng Cao'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2u.jpg',
                'year_publish'=>'2021',
                'quantity'=>'5000',
                'price'=>'95000',
                'NXB'=>'Nhà Xuất Bản Thông Tin Và Truyền Thông',
                'pages'=>'139',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'93'
            ],
            [
                'book_name'=>'Công Phá Đề Thi Học Sinh Giỏi Chuyên Đề Toán Rời Rạc Và Tổ Hợp (2015)',
                'book_slug'=>Str::slug('Công Phá Đề Thi Học Sinh Giỏi Chuyên Đề Toán Rời Rạc Và Tổ Hợp (2015)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'8647507518061.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'179000',
                'NXB'=>'Nhà Xuất Bản Thông Tin Và Truyền Thông',
                'pages'=>'139',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'94'
            ],
            [
                'book_name'=>'500 bài luyện Đọc Hiểu – Đọc Điền Tiếng Anh',
                'book_slug'=>Str::slug('500 bài luyện Đọc Hiểu – Đọc Điền Tiếng Anh'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'86619161f7d00179b0fcfce092e7c965.jpg',
                'year_publish'=>'2021',
                'quantity'=>'50',
                'price'=>'179000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'650',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'95'
            ],
            [
                'book_name'=>'Sách tiếng anh lớp 12 - Ôn tập và kiểm tra Tiếng anh tập 1 (cô Trang Anh)',
                'book_slug'=>Str::slug('Sách tiếng anh lớp 12 - Ôn tập và kiểm tra Tiếng anh tập 1 (cô Trang Anh)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'839706d4993752ec70a15996e83077bf.jpg',
                'year_publish'=>'2021',
                'quantity'=>'5000',
                'price'=>'150000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'400',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'6',
                'author_id'=>'95'
            ],
            [
                'book_name'=>'Làm Cha Mẹ Tỉnh Thức - Chuyển Hóa Bản Thân, Trao Quyền Cho Con Cái',
                'book_slug'=>Str::slug('Làm Cha Mẹ Tỉnh Thức - Chuyển Hóa Bản Thân, Trao Quyền Cho Con Cái'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'1.jpg',
                'year_publish'=>'2021',
                'quantity'=>'10',
                'price'=>'97300',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'312',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'108'
            ],
            [
                'book_name'=>'Để Con Được Ốm',
                'book_slug'=>Str::slug('Để Con Được Ốm'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2.jpg',
                'year_publish'=>'2021',
                'quantity'=>'4',
                'price'=>'61750',
                'NXB'=>null,
                'pages'=>'300',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'109'
            ],
            [
                'book_name'=>'Chờ Đến Mẫu Giáo Thì Đã Muộn',
                'book_slug'=>Str::slug('Chờ Đến Mẫu Giáo Thì Đã Muộn'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'68ee4cbb3c1b9cc2c4f4c39d54e6579c.jpg',
                'year_publish'=>'2022',
                'quantity'=>'30',
                'price'=>'51750',
                'NXB'=>'Nhà Xuất Bản Văn Học',
                'pages'=>'270',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'111'
            ],
            [
                'book_name'=>'Montessori – Phương Pháp Giáo Dục Toàn Diện Cho Trẻ 0-6 Tuổi',
                'book_slug'=>Str::slug('Montessori – Phương Pháp Giáo Dục Toàn Diện Cho Trẻ 0-6 Tuổi'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'d0c7aaa2f74d54070598ce279fa0f99e.jpg',
                'year_publish'=>'2022',
                'quantity'=>'1000',
                'price'=>'83300',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'240',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'112'
            ],
            [
                'book_name'=>'Ăn Dặm Kiểu Nhật',
                'book_slug'=>Str::slug('Ăn Dặm Kiểu Nhật'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'bef82f4d139dbea5102fe70a24bdb0d0.jpg',
                'year_publish'=>'2022',
                'quantity'=>'1000',
                'price'=>'132200',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'176',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'113'
            ],
            [
                'book_name'=>'Đọc Vị Mọi Vấn Đề Của Trẻ - Giải Mã Mọi Vấn Đề Về Nuôi Con Nhỏ: Ăn - Ngủ - Kỷ Luật Hành Vi',
                'book_slug'=>Str::slug('Đọc Vị Mọi Vấn Đề Của Trẻ - Giải Mã Mọi Vấn Đề Về Nuôi Con Nhỏ: Ăn - Ngủ - Kỷ Luật Hành Vi'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'6f314105fd1bdc7431fa278d580dc339.jpg',
                'year_publish'=>'2022',
                'quantity'=>'5',
                'price'=>'139300',
                'NXB'=>'Nhà Xuất Bản Lao Động',
                'pages'=>'512',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'7',
                'author_id'=>'114'
            ],
            [
                'book_name'=>'Cây cam ngọt của tôi',
                'book_slug'=>Str::slug('Cây cam ngọt của tôi'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'2a6154ba08df6ce6161c13f4303fa19e.jpg',
                'year_publish'=>'2022',
                'quantity'=>'1000',
                'price'=>'108000',
                'NXB'=>'Nhà xuất bản Hội Nhà Văn',
                'pages'=>'244',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'8',
                'author_id'=>'135'
            ],
            [
                'book_name'=>'Một Thoáng Ta Rực Rỡ Ở Nhân Gian',
                'book_slug'=>Str::slug('Một Thoáng Ta Rực Rỡ Ở Nhân Gian'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'a8208e9019c8510e8a8eebe06f50299c.jpg',
                'year_publish'=>'2020',
                'quantity'=>'10',
                'price'=>'135000',
                'NXB'=>'Nhà xuất bản Hội Nhà Văn',
                'pages'=>'304',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'8',
                'author_id'=>'136'
            ],
            [
                'book_name'=>'Dám Bị Ghét',
                'book_slug'=>Str::slug('Dám Bị Ghét'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'6304c47fec56e6f0b2110be65af0c7c2.jpg',
                'year_publish'=>'2021',
                'quantity'=>'8',
                'price'=>'96000',
                'NXB'=>null,
                'pages'=>'336',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'8',
                'author_id'=>'138'
            ],
            [
                'book_name'=>'Chiến Binh Cầu Vồng (Tái Bản 2020)',
                'book_slug'=>Str::slug('Chiến Binh Cầu Vồng (Tái Bản 2020)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'0b39e40dca3827604c8bc4e867cc9423.jpg',
                'year_publish'=>'2020',
                'quantity'=>'30',
                'price'=>'109000',
                'NXB'=>'Nhà xuất bản Hội Nhà Văn',
                'pages'=>'428',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'8',
                'author_id'=>'140'
            ],
            [
                'book_name'=>'Nhà Giả Kim',
                'book_slug'=>Str::slug('Nhà Giả Kim'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'737846efdb9f28f0f51352cacf9225c5.jpg',
                'year_publish'=>'2020',
                'quantity'=>'1000',
                'price'=>'64500',
                'NXB'=>'Nhà xuất bản Hội Nhà Văn',
                'pages'=>'228',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'8',
                'author_id'=>'141'
            ],
            [
                'book_name'=>'Chú Thuật Hồi Chiến: Tập 1',
                'book_slug'=>Str::slug('Chú Thuật Hồi Chiến: Tập 1'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'1b32ddda04da6a6c41aeb4a974885cf9.jpg',
                'year_publish'=>'2018',
                'quantity'=>'2500',
                'price'=>'27000',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>'192',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'9',
                'author_id'=>'156'
            ],
            [
                'book_name'=>'Thám tử lừng danh Conan Tập 99',
                'book_slug'=>Str::slug('Thám tử lừng danh Conan Tập 99'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'0c66fb626acd661f81799bde24dd9e47.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1300',
                'price'=>'20000',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>'184',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'9',
                'author_id'=>'158'
            ],
            [
                'book_name'=>'Truyện tranh - Thám tử lừng danh Conan - 5 tập/ bộ',
                'book_slug'=>Str::slug('Truyện tranh - Thám tử lừng danh Conan - 5 tập/ bộ'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'0bd417fa2852948639e5b63f3605652e.jpg',
                'year_publish'=>'2021',
                'quantity'=>'4000',
                'price'=>'99999',
                'NXB'=>'Nhà Xuất Bản Kim Đồng',
                'pages'=>null,
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'9',
                'author_id'=>'158'
            ],
            [
                'book_name'=>'Thám Tử Kindaichi (Series Kỷ Niệm 20 Năm) - Boxset 5 Tập',
                'book_slug'=>Str::slug('Thám Tử Kindaichi (Series Kỷ Niệm 20 Năm) - Boxset 5 Tập'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'174edb68dec9a3aead365c732759d5c5.jpg',
                'year_publish'=>'2020',
                'quantity'=>'50',
                'price'=>'170000',
                'NXB'=>'Nhà Xuất Bản Trẻ',
                'pages'=>null,
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'9',
                'author_id'=>'159'
            ],
            [
                'book_name'=>'Black Jack 07',
                'book_slug'=>Str::slug('Black Jack 07'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'e4757e3647a4e7999b9e2433e51e4772.jpg',
                'year_publish'=>'2022',
                'quantity'=>'1000',
                'price'=>'30000',
                'NXB'=>'Nhà Xuất Bản Trẻ',
                'pages'=>'200',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'9',
                'author_id'=>'161'
            ],
            [
                'book_name'=>'Từ Điển Tiếng Việt (Hoàng Phê)(Tái Bản)',
                'book_slug'=>Str::slug('Từ Điển Tiếng Việt (Hoàng Phê)(Tái Bản)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'96f183f0448d7390827be780fcfeeddb.jpg',
                'year_publish'=>'2022',
                'quantity'=>'40',
                'price'=>'495000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'1492',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'10',
                'author_id'=>'173'
            ],
            [
                'book_name'=>'Từ Điển Tâm Lý - Tính Cách Và Cảm Xúc Đến Từ Đâu ?',
                'book_slug'=>Str::slug('Từ Điển Tâm Lý - Tính Cách Và Cảm Xúc Đến Từ Đâu ?'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'b7f308316a5dc8de100631c979d65169.jpg',
                'year_publish'=>'2021',
                'quantity'=>'20',
                'price'=>'128000',
                'NXB'=>'Nhà Xuất Bản Thế Giới',
                'pages'=>'448',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'10',
                'author_id'=>'174'
            ],
            [
                'book_name'=>'Từ Điển Tiếng Việt Dành Cho Học Sinh',
                'book_slug'=>Str::slug('Từ Điển Tiếng Việt Dành Cho Học Sinh'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'fc96aaa69175d5f8342901944f6228b0.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'51000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'489',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'10',
                'author_id'=>'175'
            ],
            [
                'book_name'=>'Từ Điển Chính Tả Tiếng Việt ( Tác Phẩm Được Viện Ngôn Ngữ Học Thẩm Định)',
                'book_slug'=>Str::slug('Từ Điển Chính Tả Tiếng Việt ( Tác Phẩm Được Viện Ngôn Ngữ Học Thẩm Định)'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'aefedb181870adc3e0a74dbce26942aa.jpg',
                'year_publish'=>'2021',
                'quantity'=>'1000',
                'price'=>'80000',
                'NXB'=>'Nhà Xuất Bản Hồng Đức',
                'pages'=>'800',
                'is_top'=>'1',
                'status'=>'1',
                'category_id'=>'10',
                'author_id'=>'181'
            ],
            [
                'book_name'=>'Từ Điển Tiếng Việt Thông Dụng',
                'book_slug'=>Str::slug('Từ Điển Tiếng Việt Thông Dụng'),
                'description'=>null,
                'language'=>'1',
                'avatar'=>'9e5dc135ee4c3e6456243985faffdd5e.jpg',
                'year_publish'=>'2021',
                'quantity'=>'20',
                'price'=>'55000',
                'NXB'=>'Nhà Xuất Bản Dân Trí',
                'pages'=>'972',
                'is_top'=>'0',
                'status'=>'1',
                'category_id'=>'10',
                'author_id'=>'177'
            ],
        ];
        DB::table('book')->insert($Data);
    }
}
