<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $data=[
            [
                'title'=>'Chuyện con ốc sên muốn biết tại sao nó chậm chạp',
                'slug'=>Str::slug('Chuyện con ốc sên muốn biết tại sao nó chậm chạp'),
                'avatar'=>'chuyen-con-oc-sen-muon-biet-tai-sao-no-cham-chap.png',
                'description'=>"<p style='text-align: justify;'>Chuyện Con Ốc Sên Muốn Biết Tại Sao Nó Chậm Chạp ra đời từ một gợi ý rất ngộ nghĩnh khi tác giả nhận được câu hỏi của cậu cháu trai: “Ông ơi, vì sao con ốc sên lại chậm chạp như vậy?”. Được viết bởi Luis Sepulveda, tác giả đã từng rất thành công qua quyển sách Chuyện Con Mèo Dạy Hải Âu Bay – quyển sách với câu chuyện giản dị và ngộ nghĩnh nhưng ẩn chứa nhiều bài học và triết lý sâu sắc đã được hàng triệu độc giả trên thế giới đọc và cảm nhận. Ở quyển sách mới này, ông vẫn vận dụng lối viết theo kiểu ngụ ngôn, với nhân vật chính là chú ốc sên nhỏ bé và câu chuyện đi tìm khao khát và ý nghĩa cuộc sống. Chuyện Con Ốc Sên Muốn Biết Tại Sao Nó Chậm Chạp chắn chắn sẽ mang đến cho độc giả những trải nghiệm thú vị nhưng cũng đầy ý nghĩa.</p>
                <p style='text-align: center;'><img alt='Chuyện con ốc sên muốn biết tại sao nó chậm chạp' src=/description/images/post/chuyen-con-oc-sen-muon-biet-tai-sao-no-cham-chap.png></p>
                <p style='text-align: justify;'>Chuyện Con Ốc Sên Muốn Biết Tại Sao Nó Chậm Chạp kể về một chú ốc sên đã dũng cảm chấp nhận hy sinh, “tự làm khổ mình” để có thể trưởng thành hơn. Chú ốc sên này thuở nhỏ sống cùng bầy ốc sên của mình ở một nơi có tên là Quê hương Bồ Công Anh. Bọn chúng sống một cuộc đời chậm chạp, lặng lẽ, cam chịu và gọi nhau đơn giản là “sên”, cho đến khi chú ốc sên này dũng cảm nêu lên ý kiến của mình rằng cuộc đời này thật bất công khi dành sự ưu ái quá nhiều cho các loài vật khác, trong khi bọn chúng lại được “ban” cho sự chậm chạp và thậm chí không có nổi một cái tên riêng. Sau khi nêu rõ quan điểm của mình, chú đã bị đồng loại của mình chế giễu và cho rằng giống loài của chúng đã quá quen với cuộc sống chậm chạp. Để rồi từ đó, kẻ nổi loạn quyết tâm rời xa chốn thân thuộc của mình để đi tìm câu trả lời cho những thắc mắc bấy lâu.</p>                    
                <p style='text-align: justify;'>Trên chuyến hành trình ấy, chú ốc sên may mắn gặp được một bác rùa già – cũng chính là người đã đặt cho chú cái tên Dũng Khí – và chỉ dạy cho chú nhiều bài học quý giá. Và cũng nhờ cuộc hành trình đó mà chú ốc sên Dũng Khí biết được một tai họa lớn sắp ập xuống đồng cỏ – nơi các loài sinh vật và đồng loại của chú đang sống yên bình. Để rồi bằng tấm lòng yêu thương của mình, chú ốc sên nhỏ quyết định quay trở về báo tin cho đồng loại cùng như các loài vật khác như họ nhà kiến, bọ hung, chuột chũi,…</p>
                <p style='text-align: justify;'>Với giọng văn giản dị, dễ hiểu, có đôi chút hóm hỉnh kể về câu chuyện chú ốc sên Dũng Khí và những loài vật, Chuyện Con Ốc Sên Muốn Biết Tại Sao Nó Chậm Chạp phù hợp cho mọi lứa tuổi chứ không chỉ các em thiếu nhi. Bằng sự tài tình trong ngòi bút, Luis Sepulveda cũng đã vẽ ra trước mắt độc giả những hình ảnh thiên nhiên sống động với các loài vật đang sinh sống và có những suy nghĩ, tính cách khác nhau hệt như con người, qua đó mang đến cho độc giả những cảm nhận rất riêng tùy vào từng lứa tuổi hay quan niệm sống, nhưng hơn hết, sau khi đọc và ngấm những gì mà tác giả gửi gắm, mỗi người chắc chắn cũng sẽ rút ra được cho mình những bài học sâu sắc về cuộc sống, về lòng dũng cảm, khát vọng vươn lên và khẳng định cái tôi. Qua Chuyện Con Ốc Sên Muốn Biết Tại Sao Nó Chậm Chạp, mỗi người trong chúng ta thấy mình cũng giống như chú ốc sên nhỏ, hồn nhiên, nhiệt thành và như được tiếp thêm sức mạnh để sống hết mình trên chuyến hành trình tìm kiếm những điều lớn lao.</p>
                ",
                'create_at'=>'2022-04-08 20:03:10',
                'user_id'=>rand(3,502),
            ],
            [
                'title'=>'Lũ trẻ nhà Penderwicks',
                'slug'=>Str::slug('Lũ trẻ nhà Penderwicks'),
                'avatar'=>'lu-tre-nha-penderwicks.png',
                'description'=>"<p style='text-align: justify;'>Quyển sách là câu chuyện xoay quanh những thành viên trong gia đình Penderwicks với người bố “gà trống nuôi con” luôn biết lắng nghe, với chị cả Rosalind 12 tuổi – người đảm đang nhất nhà, với chị hai Skye 11 tuổi, tóc vàng mắt xanh giống mẹ – là một tài năng về các môn khoa học tự nhiên, chị ba Jane ham viết lách với giấc mơ trở thành nhà văn, bé út Batty rụt rè, nhút nhát và chú cún trung thành, đáng yêu. Tuy chỉ là những câu chuyện gần gũi và giản dị về những niềm vui, nỗi buồn trong cuộc sống cũng như những chuyến phiêu lưu mạo hiểm nhưng Lũ Trẻ Nhà Penderwicks đã hút hồn hàng triệu độc giả ở các độ tuổi khác nhau trên khắp thế giới bởi nó diễn tả được tình cảm nồng ấm giữa các thành viên trong một gia đình không còn mẹ.</p>
                <p style='text-align: center;'><img alt='Lũ trẻ nhà Penderwicks' src=/description/images/post/lu-tre-nha-penderwicks.png></p>
                <p style='text-align: justify;'>“Nếu không có chuyến đi đến một nơi nào khác biệt thì còn gọi gì là nghỉ hè nữa?”. Bắt đầu từ chân lý rất trẻ con ấy, cái tên Anrundel được chọn và cả gia đình họ gói ghém hành trang lên đường. Để rồi cuối cùng sự tình cờ thú vị ấy lại đưa họ đến với vô vàn những điều khó quên. Với lời văn giản dị và súc tích cũng như sử dụng các từ ngữ miêu tả cảm xúc thật đắc, tác giả đã như đưa người đọc vào một thế giới khác hẳn với sự xô bồ náo nhiệt hiện tại, để được đắm mình vào thiên nhiên, được trở về tuổi thơ thêm một lần nữa qua câu chuyện của nhà Penderwicks.</p>
                <p style='text-align: justify;'>Kỳ nghỉ của Lũ Trẻ Nhà Penderwicks đưa người đọc đến với dinh thự Anrundel với khu vườn mênh mông yên bình, với phòng khách lộng lẫy như một viện bảo tàng thu nhỏ, với kho báu bí mật trên căn gác cũ, những buổi vũ hội và các nàng công chúa bất đắc dĩ, hiệp sĩ đấu bò và cuộc giải vây gay cấn… Kỳ nghỉ ấy, bọn trẻ còn được gặp gỡ và kết thân với những con người đáng mến như cậu chủ nhỏ Jeffrey thân thiện, anh Cagney điểm trai, bác Harry cà chua, bác Churchie bánh gừng, và đối đầu với cả những kẻ đáng ghét như bà Tifton kênh kiệu, gã Dexter đỏm dáng nhưng xấu tính. Tuy nhiên, điểm nhấn của truyện có lẽ vẫn nằm ở những giọt nước mắt đã rơi xuống trong chuyến hành trình, khi họ đã giúp mẹ con Jeffrey hiểu nhau hơn và cậu bạn Jeffrey thoát khỏi ngôi trường quân sự quái quỷ. Có vẻ như, tất cả những cung bậc của cảm xúc đều được tác giả Jeanne Birdsall gói ghém trong câu chuyện này.</p>
                <p style='text-align: justify;'>Lũ Trẻ Nhà Penderwicks kết thúc với sự trưởng thành hơn của 4 cô bé trong truyện sau kỳ nghỉ hè, khi mà chị cả Rosalind đã bắt đầu biết lắng nghe những rung động đầu đời, Skye đã bớt nóng nảy hơn, Jane hoàn thành xuất sắc tác phẩm của mình để tiến gần hơn đến với ước mơ, và Batty không còn sợ sệt, ngơ ngác trước những người lớn chẳng mấy thân thiện.</p>
                <p style='text-align: justify;'>Lũ Trẻ Nhà Penderwicks có lẽ không phải là một câu chuyện quá cầu kỳ, nhưng nó ấn tượng bởi sự giản dị, dễ thương và gần gũi rất đời thường mà ai cũng có thể nhận ra mình giống một phần trong đó. Câu chuyện còn thu hút người đọc bởi cảnh sắc thiên nhiên thơ mộng, với nắng hè và ánh trăng đêm đêm dát bạc xuống vùng quê yên tĩnh, như giúp lòng người lắng đọng lại giữa cuộc sống bộn bề. Và hơn hết, Lũ Trẻ Nhà Penderwicks ấn tượng bởi nó mang đậm dấu ấn của một gia đình mỗi người một tính cách, một sở thích nhưng lúc nào đầy ắp tình yêu thương.</p>
                <p style='text-align: justify;'>“Đây quả là một sự trở lại những năm 1950, kỷ nguyên của những mùa hè khi bọn trẻ được du ngoạn và đọc sách. Truyền hình ư? Trò chơi điện tử ư? Hãy quên chúng đi! Lũ trẻ nhà Penderwicks mang lại niềm vui cho những độc giả trẻ tuổi, khiến họ nhớ ra một thể loại văn học của quá khứ nhưng chưa bao giờ bị quên lãng.” – Nhận định của Children Literature về tác phẩm Lũ Trẻ Nhà Penderwicks.</p>
                ",
                'create_at'=>'2022-03-08 20:15:10',
                'user_id'=>rand(3,502),
            ],
            [
                'title'=>'Em muốn có một cuộc tình già với anh',
                'slug'=>Str::slug('Em muốn có một cuộc tình già với anh'),
                'avatar'=>'em-muon-co-mot-cuoc-tinh-gia-voi-anh.png',
                'description'=>"
                <p style='text-align: justify;'>Em Muốn Có Một Cuộc Tình Già Với Anh là quyển sách thú vị và ý nghĩa được viết bởi tác giả Hoàng Anh Tú, là một trong những tác giả được yêu thích với nhiều tác phẩm quen thuộc như Mắc Kẹt Ở Thiên Đường, Thành Phố Của Những Linh Hồn Lạc,… và gần đây nhất là Yêu Là Yêu Thế Thôi và Ngã Tư Mưa, Ngã Vào Đâu Cũng Nhớ. Vẫn là những câu chuyện lãng mạn, nhẹ nhàng xen lẫn chút hài hước nhưng cũng không kém phần sâu sắc, Em Muốn Có Một Cuộc Tình Già Với Anh đúng như lời tác giả bày tỏ: “Đây là cuốn Nhật ký học yêu vợ của một anh chồng vô tâm” khi ẩn chứa rất nhiều những cung bậc cảm xúc cũng như những trải nghiệm của chính tác giả về tình yêu, hôn nhân cũng như cuộc sống hàng ngày.</p>
                <p style='text-align: center;'><img alt='Em muốn có một cuộc tình già với anh' src=/description/images/post/em-muon-co-mot-cuoc-tinh-gia-voi-anh.png></p>
                <p style='text-align: justify;>Khác với những tác phẩm trước, độc giả sẽ không tìm thấy trong Em Muốn Có Một Cuộc Tình Già Với Anh những xúc cảm ngọt ngào, lãng mạn của thuở mới yêu, cũng không bắt gặp những tiếc nuối về những mối tình đã qua hay những cơn “say nắng” dễ thương của tuổi học trò. Thay vào đó, xuyên suốt quyển sách là những cung bậc cảm xúc khác nhau của hai người đã cùng nhau nắm tay để vượt qua một chặng đường đủ dài, là những nồng nàn mà càng qua thời gian càng thêm thắm đượm, là cái khát khao to lớn để gìn giữ hôn nhân cũng như tình cảm vợ chồng luôn vững bền theo năm tháng.</p>
                <p style='text-align: justify;'>Đọc Em Muốn Có Một Cuộc Tình Già Với Anh, người đọc có thể dễ dàng bắt gặp những câu chuyện quen thuộc trong đời sống hôn nhân mà bạn đã, đang và sẽ có thể trải qua qua hình ảnh nhân vật “tôi” và “vợ”. Từ những việc nhỏ như chuyện người vợ gửi tin nhắn “tỏ tình” với chồng mình để xem phản ứng của chồng như thế nào, cho đến những luận bàn sâu sắc về đức hy sinh của người phụ nữ, cách riêng là người vợ, người mẹ trong gia đình hay thậm chí cả việc ngoại tình – vấn đề muôn thuở trong việc gìn giữ và bảo vệ hạnh phúc gia đình, đều được Hoàng Anh Tú đề cập trong quyển sách này. Qua đó, tác giả mang đến cho người đọc những chiêm nghiệm, suy nghĩ về cuộc sống, tình yêu và cuộc sống gia đình của bản thân để rồi từ đó có thể tự điều chỉnh cách ứng xử của mình để gìn giữ tình yêu của mình như ngọn lửa cháy mãi với thời gian.</p>
                <p style='text-align: justify;'>Em Muốn Có Một Cuộc Tình Già Với Anh viết về tình yêu và cuộc sống sau hôn nhân, tuy nhiên quyển sách này không chỉ dành cho những người đã là chồng, là vợ, mà còn dành cho những ai đã, đang và sẽ bước vào tình yêu. Đọc để biết, để hiểu, để chuẩn bị và sẵn sàng và đón nhận hạnh phúc. Vì như Hoàng Anh Tú đã nói: “Nếu bạn tin thì hãy mở bất cứ trang nào trong cuốn sách này để đọc. Bởi đây là một cuốn sách có thể đọc từ bất cứ trang nào. Nó giống như Hạnh Phúc, khi bạn tin, thì bất kỳ lúc nào, khi nào, ở đâu bạn cũng sẽ nhận được Hạnh Phúc!”.</p>
                ",
                'create_at'=>'2022-02-08 23:03:10',
                'user_id'=>rand(3,502),
            ],
            [
                'title'=>'Lý Gia Thành – “Ông chủ của những ông chủ”',
                'slug'=>Str::slug('Lý Gia Thành – “Ông chủ của những ông chủ”'),
                'avatar'=>'ly-gia-thanh-–-“ong-chu-cua-nhung-ong-chu”.png',
                'description'=>"
                <p style='text-align: justify;'>Lý Gia Thành – “Ông Chủ Của Những Ông Chủ” là câu chuyện đầy thú vị về cuộc đời của một con người phi thường đi lên từ thân phận nhập cư nghèo khổ, nhưng bằng tư duy sắc bén và những nỗ lực không ngừng, đã trở thành một trong 10 người giàu nhất thế giới. Nhắc đến Lý Gia Thành người ta không chỉ nhớ đến một ông vua kinh doanh tầm cỡ quốc tế – người đã đặt nền móng cho nền thương mại Hồng Kông, mà còn nghĩ ngay đến một người có lối sống cần cù, tràn đầy niềm tin, khát vọng và ý chí. Những trang sách trong Lý Gia Thành – “Ông Chủ Của Những Ông Chủ” sẽ đưa độc giả đến với những câu chuyện thú vị về ông, để rồi từ đó mỗi người sẽ rút ra được cho mình những bài học ý nghĩa về kinh doanh cũng như các mối quan hệ trong cuộc sống.</p>
                <p style='text-align: center;'><img alt='Lý Gia Thành – “Ông chủ của những ông chủ”' src=/description/images/post/ly-gia-thanh-–-“ong-chu-cua-nhung-ong-chu”.png></p>
                <p style='text-align: justify;'>Lý Gia Thành sinh ra trong một gia đình nghèo, với người cha là thầy giáo Lý Vân Kinh. Tuổi thơ của ông có thể nói là khá bất hạnh khi sinh vào “giờ xấu” theo lịch của người Trung Hoa, và ra đời ngay trong giai đoạn đất nước đang bị Nhật Bản thống trị. Và qua rất nhiều những biến cố, gia đình ông đã chuyển tới Hồng Kông để bắt đầu xây dựng một cuộc sống mới. Tuy nhiên, cuộc đời vốn không bao giờ suôn sẻ như những gì người ta vẫn nghĩ, khi gia đình chuyển đến vùng đất mới, cha của ông mắc bệnh lao và qua đời, từ đó một mình Lý Gia Thành phải bươn chải kiếm sống và gánh vác trách nhiệm với mẹ và các em. Nhờ những lời dặn dò của cha trước lúc qua đời: “Con phải có nghị lực quyết tâm. Lúc đó, con có thể với cao tới tận trời. Và hãy nhớ, bất cứ khi nào mọi việc không được như ý mình, đừng bao giờ nản chí. Đừng quên con là ai. Đừng quên nguồn gốc của con.”, từ một cậu bé nghèo khổ và có phần bất hạnh, Lý Gia Thành, nhờ sự bản lĩnh cũng như nỗ lực không ngừng của mình, đã từng bước vươn lên để trở thành một “siêu nhân kiếm tiền” nổi tiếng của mảnh đất giao thoa giữa Đông và Tây – Hồng Kông và hiện diện trong danh sách 10 nhân vật giàu nhất thế giới.</p>
                <p style='text-align: justify;'>Lý Gia Thành – “Ông Chủ Của Những Ông Chủ” không chỉ là một quyển sách chi tiết về tiểu sử và hoạt động kinh doanh của Lý Gia Thành – kể cả những giao dịch ngầm của ông, mà còn chứa rất nhiều những ý kiến, thông tin bên ngoài từ các chuyên gia kinh tế, giúp người đọc có một cái nhìn vừa tổng quát vừa cụ thể về cuộc đời của nhân vật tầm cỡ này. Những thông tin đó giúp chúng ta hiểu được vì sao một con người chỉ tập trung kinh doanh ở một thị trường bé nhỏ như Hồng Kông, lại có thể đạt được những thành công sánh ngang với các doanh nhân Mỹ và Châu Âu để bước chân vào danh sách 10 người giàu nhất thế giới. Bên cạnh những bài học quý báu về kinh doanh, khát khao thành công và những nỗ lực không ngừng, Lý Gia Thành – “Ông Chủ Của Những Ông Chủ” còn giúp người đọc hiểu ra những “chân lý” đầy giá trị trong cách sống và cách đối nhân xử thế.</p>
                <p style='text-align: justify;'>Lý Gia Thành – “Ông Chủ Của Những Ông Chủ” thật sự là một quyển sách cực kỳ thành công trong việc truyền cảm hứng đến những ai mang trong mình ngọn lửa của khát khao cháy bỏng về một thành công rực rỡ trong việc kinh doanh và cũng là một động lực mạnh mẽ cho cả những bạn trẻ mới bắt đầu khởi nghiệp. Đọc và ngấm những thông tin trong quyển sách, để hiểu được rằng cánh cửa thành công luôn rộng mở và đủ chỗ cho tất cả mọi người – những ai đủ lửa, đủ nhiệt huyết và đam mê.</p>
                ",
                'create_at'=>'2022-02-08 19:03:10',
                'user_id'=>rand(3,502),
            ],
            [
                'title'=>'Khi phụ nữ uống trà, đàn ông nên cẩn thận',
                'slug'=>Str::slug('Khi phụ nữ uống trà, đàn ông nên cẩn thận'),
                'avatar'=>'khi-phu-nu-uong-tra-dan-ong-nen-can-than.png',
                'description'=>"
                <p style='text-align: justify;'>Thế giới của phụ nữ ẩn chứa những câu chuyện mà nói mãi cũng không bao giờ hết, nhất là những phụ nữ đã, đang và sắp bước qua tuổi 30 – độ tuổi chênh vênh giữa tuổi trẻ và sự trưởng thành. Có lẽ đó cũng chính là lý do mà Phan Ý Yên đã bày tỏ rằng: “Phụ nữ trước ngưỡng 30 là một giỏ hoa nhiều sắc mà sắc nào cũng đượm một chút tiếc nuối”. Vậy thì, phải làm gì để khi chạm vào ranh giới này mà không cảm thấy tiếc nuối, chênh vênh mà có thể đón nhận ba mươi mùa xuân của mình một cách an nhiên nhất? Mời bạn cùng lắng lòng mình lại, pha một tách trà nóng với hương vị yêu thích và lần giở những trang của quyển sách Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận.</p>
                <p style='text-align: center;'><img alt='Khi phụ nữ uống trà, đàn ông nên cẩn thận' src=/description/images/post/khi-phu-nu-uong-tra-dan-ong-nen-can-than.png></p>
                <p style='text-align: justify;'>Điều ấn tượng đầu tiên không thể không nhắc đến đó là tựa đề của quyển sách – Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận – như một lời tuyên bố, thậm chí là một lời “cảnh báo” dễ thương nhưng cũng gợi sự tò mò không nhỏ. Để rồi khi cầm quyển sách trên, độc giả sẽ như được nhìn lại mình, nhìn thấy hình ảnh của những người phụ nữ mình yêu thương trong những câu chuyện về cuộc sống, sự nghiệp, tình yêu qua lăng kính của một người phụ nữ hiện đại, bản lĩnh. Vốn được biết đến là một nhà văn với những xúc cảm mỏng manh, nữ tính nhưng ở Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận, người đọc chắc chắn sẽ bắt gặp một Phan Ý Yên rất khác, táo bạo hơn, mạnh mẽ hơn nhưng cũng rất đỗi tinh tế và dịu dàng.</p>
                <p style='text-align: justify;'>Xuyên suốt gần 200 trang sách, Phan Ý Yên đã mang đến cho độc giả, đặc biệt là những độc giả nữ rất nhiều những cung bậc cảm xúc khác nhau. Khi là những rung cảm của một cô gái trẻ tha thiết yêu thương và tràn đầy hy vọng, khi lại là những suy nghĩ của một phụ nữ chín chắn, quyến rũ, mạnh mẽ và dám buông bỏ những gì không thuộc về mình, khi lại như một tấm bản đồ kho báu dẫn dắt người đọc đi tìm màu sắc cho “ngưỡng 30” của mình với “Ba mươi của bạn có màu gì?”, hoặc như một ngọn lửa thắp lên niềm tin và hy vọng trong “365 ngày may mắn”. Đọc và cảm Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận, bạn chắc chắn sẽ nhận ra rằng tuổi trẻ của chúng ta không kết thúc ở lứa tuổi 30, mà vẫn sẽ tiếp tục đến khi nào chúng ta còn biết mỉm cười vào mỗi sáng, tin rằng mình luôn còn cơ hội để bắt đầu những tháng ngày tươi đẹp ở phía trước và biết giữ trọn vẹn thanh xuân ngay trong chính tim mình. Không những thế, đâu đó trong quyển sách này, bạn cũng sẽ tìm được cho mình thêm động lực để “dám” chấp nhận, can đảm từ bỏ và nhận ra hạnh phúc từ chính những cú ngã, những nỗi đau.</p>
                <p style='text-align: justify;'>Bằng giọng văn gần gũi, nhẹ nhàng như lời tâm tình của những người phụ nữ trong những cuộc trà, Phan Ý Yên đã sẻ chia với phụ nữ 30 những điều họ lo lắng nhất, trăn trở nhất về tình yêu, về trưởng thành, về được – mất trong cuộc sống thường nhật. Nhưng khác với những nỗi buồn da diết thường thấy trong các tác phẩm trước của cô, bất cứ ai khi đọc xong Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận, chắc chắn cũng sẽ tìm thấy cho mình thêm sự lạc quan và niềm tin vào cuộc sống, vào tình yêu cũng như tin vào chính bản thân mình khi đối diện với bất cứ vấn đề nào của cuộc sống.</p>
                <p style='text-align: justify;'>Khi Phụ Nữ Uống Trà, Đàn Ông Nên Cẩn Thận không chỉ là món quà dành riêng cho những ai chuẩn bị đón tuổi 30 của mình, vì dù bạn đang bao nhiêu tuổi thì đây vẫn sẽ là một quyển cẩm nang nhỏ xinh mang đến cho bạn những thông tin cũng như phần nào đó kiến thức để bạn thêm tự tin và an nhiên đón tuổi mới. Hãy mở lòng ra và cảm nhận, bạn sẽ thấy mình chưa bao giờ đơn độc trên con đường trưởng thành và yêu thương.</p>
                <p style='text-align: justify;'>Phải sống đủ lâu, trải nghiệm đủ dài mới có đủ bản lĩnh để đối diện với tất cả sự thật lẫn không thật trong cuộc sống này. Xét cho cùng, không phải những gì trần trụi khiến bạn đau lòng hay mất mát mà chính là cách chúng ta chọn đối diện và giải quyết chúng. Không có niềm đau vĩnh viễn hay tổn thất không thể đắp bù. Chỉ có trái tim con người chịu tha thứ, buông bỏ hay hàn gắn hay không mà thôi. Vì vậy, đôi lúc, một nửa của sự thật cũng đủ là sự thật rồi. Bạn có nghĩ vậy không?</p>
                ",
                'create_at'=>'2021-02-08 19:50:10',
                'user_id'=>rand(3,502),
            ],
        ];
        DB::table('post')->insert($data);
    }
}
